# 智能文档内容提取服务配置文件

templates_dir = "templates"
default_template = "default"

[llm]
# LLM API端点配置
api_endpoint = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
# API密钥（建议通过环境变量 LLM_API_KEY 设置）
api_key = "sk-123456"
# 使用的模型名称
model = "qwen-plus-2025-09-11"
# 最大token数
max_tokens = 32768
# 温度参数（0.0-2.0）
temperature = 0.0
# 请求超时时间（秒）
timeout_seconds = 1200

# 自定义HTTP头部（可选）
# [[llm.headers]]
# name = "Authorization"
# value = "Bearer your-token"

[server]
# 服务器配置
host = "127.0.0.1"
port = 8080
# 最大连接数
max_connections = 100
# 请求超时时间（秒）
request_timeout_seconds = 6000

[processing]
# 文档处理配置
# 最大文档大小（MB）
max_document_size_mb = 10.0
# 内容分块大小
chunk_size = 40000
# 支持的文件格式
supported_formats = ["txt", "md", "json", "yaml", "yml", "toml", "xml", "csv"]
# 是否启用预处理
enable_preprocessing = true

[processing.cleaning]
# 文档清理配置
# 是否启用清理功能
enable_cleaning = true
# 是否移除base64编码图片
remove_base64_images = true
# 是否移除二进制数据
remove_binary_data = true
# 最大字符串长度（超过将被截断）
max_string_length = 1000
# 是否移除HTML标签
remove_html_tags = true
# 是否规范化空白字符
normalize_whitespace = true
# 自定义清理模式（正则表达式）
custom_patterns = [
    # 移除连续的标点符号
    "[.]{3,}",
    "[!]{2,}",
    "[?]{2,}",
    # 移除长数字序列
    "\\b\\d{10,}\\b",
    # 移除长字母序列
    "\\b[a-zA-Z]{20,}\\b"
]
